package com.nandi.yngsagp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nandi.yngsagp.bean.DisasterUBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISASTER_UBEAN".
*/
public class DisasterUBeanDao extends AbstractDao<DisasterUBean, Long> {

    public static final String TABLENAME = "DISASTER_UBEAN";

    /**
     * Properties of entity DisasterUBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ReportMan = new Property(1, String.class, "reportMan", false, "REPORT_MAN");
        public final static Property Phone = new Property(2, String.class, "phone", false, "PHONE");
        public final static Property Time = new Property(3, String.class, "time", false, "TIME");
        public final static Property Address = new Property(4, String.class, "address", false, "ADDRESS");
        public final static Property Location = new Property(5, String.class, "location", false, "LOCATION");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property Factor = new Property(7, String.class, "factor", false, "FACTOR");
        public final static Property Injured = new Property(8, String.class, "injured", false, "INJURED");
        public final static Property Death = new Property(9, String.class, "death", false, "DEATH");
        public final static Property Miss = new Property(10, String.class, "miss", false, "MISS");
        public final static Property Farm = new Property(11, String.class, "farm", false, "FARM");
        public final static Property House = new Property(12, String.class, "house", false, "HOUSE");
        public final static Property Money = new Property(13, String.class, "money", false, "MONEY");
        public final static Property Lon = new Property(14, String.class, "lon", false, "LON");
        public final static Property Lat = new Property(15, String.class, "lat", false, "LAT");
        public final static Property Other = new Property(16, String.class, "other", false, "OTHER");
        public final static Property ReportName = new Property(17, String.class, "reportName", false, "REPORT_NAME");
        public final static Property ReportMobile = new Property(18, String.class, "reportMobile", false, "REPORT_MOBILE");
        public final static Property DisasterPosition = new Property(19, int.class, "disasterPosition", false, "DISASTER_POSITION");
    }


    public DisasterUBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DisasterUBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISASTER_UBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REPORT_MAN\" TEXT," + // 1: reportMan
                "\"PHONE\" TEXT," + // 2: phone
                "\"TIME\" TEXT," + // 3: time
                "\"ADDRESS\" TEXT," + // 4: address
                "\"LOCATION\" TEXT," + // 5: location
                "\"TYPE\" TEXT," + // 6: type
                "\"FACTOR\" TEXT," + // 7: factor
                "\"INJURED\" TEXT," + // 8: injured
                "\"DEATH\" TEXT," + // 9: death
                "\"MISS\" TEXT," + // 10: miss
                "\"FARM\" TEXT," + // 11: farm
                "\"HOUSE\" TEXT," + // 12: house
                "\"MONEY\" TEXT," + // 13: money
                "\"LON\" TEXT," + // 14: lon
                "\"LAT\" TEXT," + // 15: lat
                "\"OTHER\" TEXT," + // 16: other
                "\"REPORT_NAME\" TEXT," + // 17: reportName
                "\"REPORT_MOBILE\" TEXT," + // 18: reportMobile
                "\"DISASTER_POSITION\" INTEGER NOT NULL );"); // 19: disasterPosition
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISASTER_UBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DisasterUBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String reportMan = entity.getReportMan();
        if (reportMan != null) {
            stmt.bindString(2, reportMan);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(3, phone);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(4, time);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(5, address);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(6, location);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
 
        String factor = entity.getFactor();
        if (factor != null) {
            stmt.bindString(8, factor);
        }
 
        String injured = entity.getInjured();
        if (injured != null) {
            stmt.bindString(9, injured);
        }
 
        String death = entity.getDeath();
        if (death != null) {
            stmt.bindString(10, death);
        }
 
        String miss = entity.getMiss();
        if (miss != null) {
            stmt.bindString(11, miss);
        }
 
        String farm = entity.getFarm();
        if (farm != null) {
            stmt.bindString(12, farm);
        }
 
        String house = entity.getHouse();
        if (house != null) {
            stmt.bindString(13, house);
        }
 
        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(14, money);
        }
 
        String lon = entity.getLon();
        if (lon != null) {
            stmt.bindString(15, lon);
        }
 
        String lat = entity.getLat();
        if (lat != null) {
            stmt.bindString(16, lat);
        }
 
        String other = entity.getOther();
        if (other != null) {
            stmt.bindString(17, other);
        }
 
        String reportName = entity.getReportName();
        if (reportName != null) {
            stmt.bindString(18, reportName);
        }
 
        String reportMobile = entity.getReportMobile();
        if (reportMobile != null) {
            stmt.bindString(19, reportMobile);
        }
        stmt.bindLong(20, entity.getDisasterPosition());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DisasterUBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String reportMan = entity.getReportMan();
        if (reportMan != null) {
            stmt.bindString(2, reportMan);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(3, phone);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(4, time);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(5, address);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(6, location);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
 
        String factor = entity.getFactor();
        if (factor != null) {
            stmt.bindString(8, factor);
        }
 
        String injured = entity.getInjured();
        if (injured != null) {
            stmt.bindString(9, injured);
        }
 
        String death = entity.getDeath();
        if (death != null) {
            stmt.bindString(10, death);
        }
 
        String miss = entity.getMiss();
        if (miss != null) {
            stmt.bindString(11, miss);
        }
 
        String farm = entity.getFarm();
        if (farm != null) {
            stmt.bindString(12, farm);
        }
 
        String house = entity.getHouse();
        if (house != null) {
            stmt.bindString(13, house);
        }
 
        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(14, money);
        }
 
        String lon = entity.getLon();
        if (lon != null) {
            stmt.bindString(15, lon);
        }
 
        String lat = entity.getLat();
        if (lat != null) {
            stmt.bindString(16, lat);
        }
 
        String other = entity.getOther();
        if (other != null) {
            stmt.bindString(17, other);
        }
 
        String reportName = entity.getReportName();
        if (reportName != null) {
            stmt.bindString(18, reportName);
        }
 
        String reportMobile = entity.getReportMobile();
        if (reportMobile != null) {
            stmt.bindString(19, reportMobile);
        }
        stmt.bindLong(20, entity.getDisasterPosition());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DisasterUBean readEntity(Cursor cursor, int offset) {
        DisasterUBean entity = new DisasterUBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // reportMan
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // phone
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // time
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // address
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // location
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // factor
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // injured
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // death
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // miss
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // farm
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // house
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // money
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // lon
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // lat
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // other
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // reportName
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // reportMobile
            cursor.getInt(offset + 19) // disasterPosition
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DisasterUBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReportMan(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPhone(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAddress(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLocation(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFactor(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setInjured(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDeath(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMiss(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFarm(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setHouse(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMoney(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setLon(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setLat(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setOther(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setReportName(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setReportMobile(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDisasterPosition(cursor.getInt(offset + 19));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DisasterUBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DisasterUBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DisasterUBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
