package com.nandi.yngsagp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nandi.yngsagp.bean.DisasterPoint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISASTER_POINT".
*/
public class DisasterPointDao extends AbstractDao<DisasterPoint, Long> {

    public static final String TABLENAME = "DISASTER_POINT";

    /**
     * Properties of entity DisasterPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DisName = new Property(1, String.class, "disName", false, "DIS_NAME");
        public final static Property DisId = new Property(2, String.class, "disId", false, "DIS_ID");
    }


    public DisasterPointDao(DaoConfig config) {
        super(config);
    }
    
    public DisasterPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISASTER_POINT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DIS_NAME\" TEXT," + // 1: disName
                "\"DIS_ID\" TEXT);"); // 2: disId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISASTER_POINT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DisasterPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String disName = entity.getDisName();
        if (disName != null) {
            stmt.bindString(2, disName);
        }
 
        String disId = entity.getDisId();
        if (disId != null) {
            stmt.bindString(3, disId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DisasterPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String disName = entity.getDisName();
        if (disName != null) {
            stmt.bindString(2, disName);
        }
 
        String disId = entity.getDisId();
        if (disId != null) {
            stmt.bindString(3, disId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DisasterPoint readEntity(Cursor cursor, int offset) {
        DisasterPoint entity = new DisasterPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // disName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // disId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DisasterPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDisName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDisId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DisasterPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DisasterPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DisasterPoint entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
